from __future__ import annotations

from salt.rules.patterns import PatternRuleSpec, build_pattern_rule_class


UVM_COMMUNITY_SPECS: list[PatternRuleSpec] = [
    PatternRuleSpec("UVM003", "uvm_no_do_macro", "Discourage `uvm_do macros.", "Use explicit create/start/randomize flow instead of `uvm_do.", r"`uvm_do(?:_|\b)", "warning"),
    PatternRuleSpec("UVM004", "uvm_no_do_on_macro", "Discourage `uvm_do_on macros.", "Use explicit sequencer targeting instead of `uvm_do_on.", r"`uvm_do_on\b", "warning"),
    PatternRuleSpec("UVM005", "uvm_no_do_with_macro", "Discourage `uvm_do_with macros.", "Use explicit randomize with constraints instead of `uvm_do_with.", r"`uvm_do(?:_on)?_with\b", "warning"),
    PatternRuleSpec("UVM006", "uvm_no_send_macro", "Discourage `uvm_send macros.", "Use explicit start_item/finish_item or sequence start flow.", r"`uvm_send\b", "warning"),
    PatternRuleSpec("UVM007", "uvm_no_rand_send_macro", "Discourage `uvm_rand_send macros.", "Use explicit randomize and send flow instead of `uvm_rand_send.", r"`uvm_rand_send\b", "warning"),
    PatternRuleSpec("UVM008", "uvm_no_create_macro", "Discourage `uvm_create macros.", "Use type_id::create directly for clearer factory behavior.", r"`uvm_create\b", "info"),
    PatternRuleSpec("UVM009", "uvm_no_resource_db", "Discourage uvm_resource_db.", "Prefer uvm_config_db with scoped paths instead of uvm_resource_db.", r"\buvm_resource_db\s*#", "warning"),
    PatternRuleSpec("UVM010", "uvm_no_config_db_wildcard_set", "Discourage wildcard config_db sets.", "Avoid config_db set paths with '*' because they hide ownership.", r"uvm_config_db\s*#.*::\s*set\s*\([^,]+,\s*\"[^\"]*\*", "warning"),
    PatternRuleSpec("UVM011", "uvm_no_config_db_null_context", "Discourage null config_db context.", "Use a component context for config_db access instead of null.", r"uvm_config_db\s*#.*::\s*(?:get|set)\s*\(\s*null\s*,", "warning"),
    PatternRuleSpec("UVM012", "uvm_no_set_config_int", "Disallow legacy set_config_int.", "Use uvm_config_db instead of set_config_int.", r"\bset_config_int\s*\(", "warning"),
    PatternRuleSpec("UVM013", "uvm_no_set_config_string", "Disallow legacy set_config_string.", "Use uvm_config_db instead of set_config_string.", r"\bset_config_string\s*\(", "warning"),
    PatternRuleSpec("UVM014", "uvm_no_set_config_object", "Disallow legacy set_config_object.", "Use uvm_config_db instead of set_config_object.", r"\bset_config_object\s*\(", "warning"),
    PatternRuleSpec("UVM015", "uvm_no_get_config_int", "Disallow legacy get_config_int.", "Use uvm_config_db instead of get_config_int.", r"\bget_config_int\s*\(", "warning"),
    PatternRuleSpec("UVM016", "uvm_no_get_config_string", "Disallow legacy get_config_string.", "Use uvm_config_db instead of get_config_string.", r"\bget_config_string\s*\(", "warning"),
    PatternRuleSpec("UVM017", "uvm_no_get_config_object", "Disallow legacy get_config_object.", "Use uvm_config_db instead of get_config_object.", r"\bget_config_object\s*\(", "warning"),
    PatternRuleSpec("UVM018", "uvm_no_global_timeout_zero", "Discourage zero global timeout.", "Do not disable UVM timeout with a zero value.", r"\bset_global_timeout\s*\(\s*0\b", "warning"),
    PatternRuleSpec("UVM019", "uvm_no_stop_request", "Disallow deprecated global stop request.", "Use phase objections and drain time instead of uvm_stop_request.", r"\buvm_stop_request\s*\(", "warning"),
    PatternRuleSpec("UVM020", "uvm_no_global_stop_request", "Disallow deprecated global stop request API.", "Use phase objections instead of global_stop_request.", r"\bglobal_stop_request\s*\(", "warning"),
    PatternRuleSpec("UVM021", "uvm_no_objection_in_sequence", "Discourage objections in sequences.", "Raise/drop objections in components or tests, not sequence bodies.", r"class\s+[A-Za-z_]\w*\s+extends\s+uvm_sequence[\s\S]*\.(?:raise|drop)_objection\s*\(", "warning", "forbidden_file"),
    PatternRuleSpec("UVM022", "uvm_no_phase_jump", "Discourage phase jumps.", "Avoid phase jumps; model reset and recovery with explicit components.", r"\.jump\s*\(", "warning"),
    PatternRuleSpec("UVM023", "uvm_no_direct_root_access", "Discourage direct uvm_root access.", "Avoid uvm_root::get for normal testbench coordination.", r"\buvm_root::get\s*\(", "info"),
    PatternRuleSpec("UVM024", "uvm_no_top_access", "Discourage uvm_top access.", "Avoid global uvm_top access except in reviewed infrastructure code.", r"\buvm_top\b", "info"),
    PatternRuleSpec("UVM025", "uvm_no_report_server_global", "Discourage direct report_server mutation.", "Configure reporting through scoped report APIs instead of global server mutation.", r"\buvm_report_server::get_server\s*\(", "warning"),
    PatternRuleSpec("UVM026", "uvm_no_display", "Disallow $display in UVM code.", "Use `uvm_info, `uvm_warning, `uvm_error, or `uvm_fatal instead of $display.", r"\$display\s*\(", "warning"),
    PatternRuleSpec("UVM027", "uvm_no_write", "Disallow $write in UVM code.", "Use UVM reporting instead of $write.", r"\$write\s*\(", "warning"),
    PatternRuleSpec("UVM028", "uvm_no_strobe", "Disallow $strobe in UVM code.", "Use UVM reporting instead of $strobe.", r"\$strobe\s*\(", "warning"),
    PatternRuleSpec("UVM029", "uvm_no_finish", "Disallow $finish in UVM code.", "End tests with objections and phase completion instead of $finish.", r"\$finish\s*(?:\(|;)", "error"),
    PatternRuleSpec("UVM030", "uvm_no_stop", "Disallow $stop in UVM code.", "Use UVM fatal/error reporting and controlled shutdown instead of $stop.", r"\$stop\s*(?:\(|;)", "error"),
    PatternRuleSpec("UVM031", "uvm_no_fatal_without_id", "Discourage generic uvm_fatal IDs.", "Use a specific message ID for `uvm_fatal.", r"`uvm_fatal\s*\(\s*\"(?:|FATAL|ERROR|UVM_FATAL)\"", "warning"),
    PatternRuleSpec("UVM032", "uvm_no_error_without_id", "Discourage generic uvm_error IDs.", "Use a specific message ID for `uvm_error.", r"`uvm_error\s*\(\s*\"(?:|ERROR|UVM_ERROR)\"", "warning"),
    PatternRuleSpec("UVM033", "uvm_no_info_none", "Discourage UVM_NONE info verbosity.", "Use an intentional verbosity such as UVM_LOW, UVM_MEDIUM, or UVM_HIGH.", r"`uvm_info\s*\([^,]+,[^,]+,\s*UVM_NONE\s*\)", "info"),
    PatternRuleSpec("UVM034", "uvm_no_info_high_in_loops", "Discourage high-verbosity loop spam.", "Avoid `uvm_info inside tight loops unless explicitly throttled.", r"\b(?:for|foreach|while)\s*\([^)]*\)[\s\S]*`uvm_info", "info", "forbidden_file"),
    PatternRuleSpec("UVM035", "uvm_no_component_new_without_parent", "Require component constructors to take parent.", "UVM component constructors should include a parent argument.", r"function\s+new\s*\(\s*string\s+name\s*=\s*\"[^\"]*\"\s*\)", "warning"),
    PatternRuleSpec("UVM036", "uvm_no_object_new_with_parent", "Discourage parent arguments in object constructors.", "UVM object constructors should only take a name argument.", r"class\s+[A-Za-z_]\w*\s+extends\s+uvm_(?:sequence_item|object|sequence)[\s\S]*function\s+new\s*\([^)]*uvm_component\s+parent", "warning", "forbidden_file"),
    PatternRuleSpec("UVM037", "uvm_no_direct_component_new", "Discourage direct UVM component construction.", "Create components through type_id::create to preserve factory override behavior.", r"\bnew\s*\([^)]*\bthis\s*\)", "warning"),
    PatternRuleSpec("UVM038", "uvm_no_direct_object_new", "Discourage direct UVM object construction.", "Create UVM objects through type_id::create unless bypassing the factory is intentional.", r"\b[A-Za-z_]\w*\s*=\s*new\s*\(", "info"),
    PatternRuleSpec("UVM039", "uvm_no_missing_super_build", "Require super.build_phase when build_phase exists.", "Call super.build_phase(phase) in build_phase.", r"function\s+void\s+build_phase\s*\(", "warning", "required_file_if", r"super\.build_phase\s*\(\s*phase\s*\)"),
    PatternRuleSpec("UVM040", "uvm_no_missing_super_connect", "Require super.connect_phase when connect_phase exists.", "Call super.connect_phase(phase) in connect_phase.", r"function\s+void\s+connect_phase\s*\(", "warning", "required_file_if", r"super\.connect_phase\s*\(\s*phase\s*\)"),
    PatternRuleSpec("UVM041", "uvm_no_missing_super_run", "Require super.run_phase when run_phase exists.", "Call super.run_phase(phase) in run_phase when overriding it.", r"task\s+run_phase\s*\(", "info", "required_file_if", r"super\.run_phase\s*\(\s*phase\s*\)"),
    PatternRuleSpec("UVM042", "uvm_no_get_without_check", "Discourage unchecked config_db get.", "Check the return value of uvm_config_db::get.", r"\bvoid'\s*\(\s*uvm_config_db\s*#.*::\s*get\s*\(", "warning"),
    PatternRuleSpec("UVM043", "uvm_no_analysis_imp_write_empty", "Discourage empty analysis write methods.", "Implement analysis write methods or remove the unused analysis imp.", r"function\s+void\s+write\s*\([^)]*\)\s*;\s*endfunction", "warning"),
    PatternRuleSpec("UVM044", "uvm_no_sequence_start_null", "Discourage sequence start(null).", "Start sequences on an explicit sequencer.", r"\.start\s*\(\s*null\s*\)", "warning"),
    PatternRuleSpec("UVM045", "uvm_no_sequencer_arbitration_fifo", "Discourage hard-coded FIFO arbitration.", "Avoid hard-coding sequencer arbitration unless the test requires it.", r"\.set_arbitration\s*\(\s*UVM_SEQ_ARB_FIFO\s*\)", "info"),
    PatternRuleSpec("UVM046", "uvm_no_default_sequence", "Discourage default_sequence config.", "Prefer explicit virtual sequence starts over default_sequence configuration.", r"\"default_sequence\"", "warning"),
    PatternRuleSpec("UVM047", "uvm_no_p_sequencer_macro", "Discourage `uvm_declare_p_sequencer.", "Prefer explicit sequencer handles over `uvm_declare_p_sequencer coupling.", r"`uvm_declare_p_sequencer\b", "info"),
    PatternRuleSpec("UVM048", "uvm_no_field_automation", "Discourage field automation macros.", "Implement do_copy/do_compare/do_print intentionally instead of field automation macros.", r"`uvm_field_(?:int|enum|object|string|array|queue|sarray|aa)_", "info"),
    PatternRuleSpec("UVM049", "uvm_no_config_object_clone_zero", "Discourage config object set without clone.", "Clone mutable config objects before sharing them through config_db.", r"uvm_config_db\s*#.*::\s*set\s*\([^;]*\b[A-Za-z_]\w*_cfg\b", "info"),
    PatternRuleSpec("UVM050", "uvm_no_hardcoded_testname", "Discourage hard-coded run_test names.", "Pass test names from the simulator command line instead of hard-coding run_test.", r"\brun_test\s*\(\s*\"[^\"]+\"\s*\)", "warning"),
    PatternRuleSpec("UVM051", "uvm_no_empty_run_phase", "Discourage empty run_phase methods.", "Remove empty run_phase overrides.", r"task\s+run_phase\s*\([^)]*\)\s*;\s*endtask", "warning"),
    PatternRuleSpec("UVM052", "uvm_no_missing_factory_create", "Require factory create in files with UVM classes.", "Use type_id::create in files that declare UVM classes.", r"class\s+[A-Za-z_]\w*\s+extends\s+uvm_", "info", "required_file_if", r"::type_id::create\s*\("),
]

UVM_COMMUNITY_RULES = [build_pattern_rule_class(spec) for spec in UVM_COMMUNITY_SPECS]
