from __future__ import annotations

from salt.rules.patterns import PatternRuleSpec, build_pattern_rule_class


SV_COMMUNITY_SPECS: list[PatternRuleSpec] = [
    PatternRuleSpec("SV005", "no_defparam", "Disallow defparam overrides.", "Use parameter overrides at instantiation instead of defparam.", r"\bdefparam\b", "error"),
    PatternRuleSpec("SV006", "no_wildcard_import", "Disallow wildcard package imports.", "Import explicit package symbols instead of using wildcard imports.", r"\bimport\s+[A-Za-z_]\w*::\*", "warning"),
    PatternRuleSpec("SV007", "no_wildcard_port_connection", "Disallow .* instance port connections.", "Use explicit named port connections instead of .*.", r"\.\*", "warning"),
    PatternRuleSpec("SV008", "no_force_statement", "Disallow force statements in checked code.", "Avoid force; use a controlled testbench hook or proper driver.", r"\bforce\b", "warning"),
    PatternRuleSpec("SV009", "no_release_statement", "Disallow release statements in checked code.", "Avoid release; remove the paired force usage.", r"\brelease\b", "warning"),
    PatternRuleSpec("SV010", "no_wait_statement", "Discourage unbounded wait statements.", "Use event controls, clocking blocks, or bounded waits instead of wait().", r"\bwait\s*\(", "warning"),
    PatternRuleSpec("SV011", "no_join_none", "Discourage fork/join_none.", "Use structured process lifetime management instead of join_none.", r"\bjoin_none\b", "warning"),
    PatternRuleSpec("SV012", "no_disable_fork", "Discourage disable fork.", "Avoid disable fork; keep process ownership explicit.", r"\bdisable\s+fork\b", "warning"),
    PatternRuleSpec("SV013", "no_deassign_statement", "Disallow deassign statements.", "Avoid deassign; use synthesizable procedural assignments.", r"\bdeassign\b", "error"),
    PatternRuleSpec("SV014", "no_drive_strength", "Discourage drive strength annotations.", "Avoid drive strengths in portable RTL and verification code.", r"\((?:supply|strong|pull|weak|highz)[01]", "warning"),
    PatternRuleSpec("SV015", "no_internal_tristate_net", "Discourage tri-state net types.", "Avoid internal tri-state nets; use muxed logic unless this is an IO boundary.", r"\btri(?:0|1|and|or|reg)?\b", "warning"),
    PatternRuleSpec("SV016", "no_casez", "Discourage casez because z wildcards can hide bugs.", "Prefer case/inside with explicit masks instead of casez.", r"\bcasez\b", "warning"),
    PatternRuleSpec("SV017", "no_full_case_parallel_case", "Disallow full_case/parallel_case pragmas.", "Use unique/priority semantics instead of full_case or parallel_case pragmas.", r"\b(?:full_case|parallel_case)\b", "error"),
    PatternRuleSpec("SV018", "no_translate_off", "Discourage synthesis translate_off regions.", "Avoid translate_off regions in linted source; isolate simulation-only code.", r"\btranslate_off\b", "warning"),
    PatternRuleSpec("SV019", "no_mixed_edge_event_control", "Discourage mixed posedge/negedge event controls.", "Avoid mixing posedge and negedge in the same event control.", r"@\s*\([^)]*(?:posedge[^)]*negedge|negedge[^)]*posedge)", "warning"),
    PatternRuleSpec("SV020", "no_always_latch", "Discourage intentional latch blocks.", "Avoid always_latch unless the design intentionally requires a latch.", r"\balways_latch\b", "warning"),
    PatternRuleSpec("SV021", "no_x_assignment", "Discourage assigning x values.", "Avoid assigning X values in checked source.", r"(?:<=|=)\s*(?:\d+)?'?[bodh]?[xX]", "warning"),
    PatternRuleSpec("SV022", "no_z_assignment", "Discourage assigning z values.", "Avoid assigning Z values except at explicit IO tri-state boundaries.", r"(?:<=|=)\s*(?:\d+)?'?[bodh]?[zZ]", "warning"),
    PatternRuleSpec("SV023", "no_real_type", "Discourage real variables in portable code.", "Avoid real variables in linted source.", r"\breal\s+[A-Za-z_]\w*", "warning"),
    PatternRuleSpec("SV024", "no_realtime_type", "Discourage realtime variables in portable code.", "Avoid realtime variables in linted source.", r"\brealtime\s+[A-Za-z_]\w*", "warning"),
    PatternRuleSpec("SV025", "no_shortreal_type", "Discourage shortreal variables in portable code.", "Avoid shortreal variables in linted source.", r"\bshortreal\s+[A-Za-z_]\w*", "warning"),
    PatternRuleSpec("SV026", "no_event_variable", "Discourage raw event variables.", "Prefer typed transactions, mailboxes, or analysis ports over raw event variables.", r"\bevent\s+[A-Za-z_]\w*", "warning"),
    PatternRuleSpec("SV027", "no_mailbox", "Discourage mailbox usage in shared code.", "Prefer typed FIFOs or UVM TLM channels instead of mailbox.", r"\bmailbox\b", "warning"),
    PatternRuleSpec("SV028", "no_semaphore", "Discourage semaphore usage in shared code.", "Prefer clearer ownership protocols instead of semaphore.", r"\bsemaphore\b", "warning"),
    PatternRuleSpec("SV029", "no_process_class", "Discourage direct process handle usage.", "Avoid process handles unless process control is tightly reviewed.", r"\bprocess\b", "warning"),
    PatternRuleSpec("SV030", "no_randomize_in_rtl", "Discourage randomize calls in linted source.", "Keep randomization in controlled verification code.", r"\.randomize\s*\(", "warning"),
    PatternRuleSpec("SV031", "no_randcase", "Discourage randcase.", "Use explicit constrained random stimulus instead of randcase.", r"\brandcase\b", "warning"),
    PatternRuleSpec("SV032", "no_randsequence", "Discourage randsequence.", "Use explicit sequence objects or constrained random code instead of randsequence.", r"\brandsequence\b", "warning"),
    PatternRuleSpec("SV033", "no_program_block", "Disallow program blocks.", "Use modules, interfaces, packages, and classes instead of program blocks.", r"^\s*program\b", "error"),
    PatternRuleSpec("SV034", "no_implicit_event_or", "Discourage comma-separated event controls.", "Use explicit 'or' event controls or a clocking block for readability.", r"@\s*\([^)]*,[^)]*\)", "warning"),
    PatternRuleSpec("SV035", "no_unnamed_begin", "Discourage unnamed begin blocks.", "Name nontrivial begin blocks to improve traceability.", r"^\s*begin\s*(?:$|//)", "info"),
    PatternRuleSpec("SV036", "no_unnamed_fork", "Discourage unnamed fork blocks.", "Name fork blocks when process control or debug visibility matters.", r"^\s*fork\s*(?:$|//)", "info"),
    PatternRuleSpec("SV037", "no_positional_parameter_override", "Discourage positional parameter overrides.", "Use named parameter overrides for maintainable instances.", r"#\s*\(\s*[^.][^)]*\)\s+[A-Za-z_]\w*\s+[A-Za-z_]\w*\s*\(", "warning"),
    PatternRuleSpec("SV038", "no_positional_task_call_delay", "Discourage delay before task calls.", "Avoid fixed delays before task calls; synchronize to protocol events.", r"#\s*\d+\s*;?\s*[A-Za-z_]\w*\s*\(", "warning"),
    PatternRuleSpec("SV039", "no_hash_delay", "Discourage arbitrary # delays.", "Avoid arbitrary # delays in linted source.", r"(?<!#)#\s*\d+", "warning"),
    PatternRuleSpec("SV040", "no_disable_statement", "Discourage disable statements.", "Avoid disable; use structured control flow.", r"\bdisable\s+[A-Za-z_]\w*", "warning"),
    PatternRuleSpec("SV041", "no_wait_fork", "Discourage wait fork.", "Avoid wait fork; keep process joins explicit.", r"\bwait\s+fork\b", "warning"),
    PatternRuleSpec("SV042", "no_expect_statement", "Discourage expect statements.", "Use assertions or explicit checks instead of expect.", r"\bexpect\s*\(", "warning"),
    PatternRuleSpec("SV043", "no_final_block", "Discourage final blocks in shared source.", "Prefer explicit end-of-test reporting over final blocks.", r"^\s*final\b", "warning"),
    PatternRuleSpec("SV044", "no_inc_dec_in_expression", "Discourage increment/decrement operators.", "Use explicit assignments instead of ++ or -- for clearer intent.", r"(?:\+\+|--)", "info"),
    PatternRuleSpec("SV045", "no_macro_definition_in_source", "Discourage local macro definitions.", "Centralize macros in shared include files or packages.", r"^\s*`define\b", "warning"),
    PatternRuleSpec("SV046", "no_include_in_source", "Discourage include directives.", "Prefer packages and explicit compilation units over textual includes.", r"^\s*`include\b", "warning"),
    PatternRuleSpec("SV047", "no_timescale_in_source", "Discourage timescale directives.", "Set timeunit/timeprecision in source instead of `timescale.", r"^\s*`timescale\b", "warning"),
    PatternRuleSpec("SV048", "no_untyped_parameter", "Discourage untyped parameters.", "Declare parameter types explicitly.", r"\bparameter\s+(?!type\b)(?!integer\b)(?!int\b)(?!logic\b)(?!bit\b)(?!real\b)[A-Za-z_]\w*\s*=", "warning"),
    PatternRuleSpec("SV049", "no_untyped_localparam", "Discourage untyped localparams.", "Declare localparam types explicitly.", r"\blocalparam\s+(?!type\b)(?!integer\b)(?!int\b)(?!logic\b)(?!bit\b)(?!real\b)[A-Za-z_]\w*\s*=", "warning"),
    PatternRuleSpec("SV050", "no_legacy_reg", "Discourage legacy reg declarations.", "Use logic for SystemVerilog variables instead of reg.", r"\breg\s+(?:signed\s+)?(?:\[[^]]+\]\s*)?[A-Za-z_]\w*", "warning"),
    PatternRuleSpec("SV051", "no_legacy_wire_for_variables", "Discourage wire declarations for internal variables.", "Use logic for internal variables; keep wire for nets that need net semantics.", r"\bwire\s+(?:signed\s+)?(?:\[[^]]+\]\s*)?[A-Za-z_]\w*", "info"),
    PatternRuleSpec("SV052", "no_assign_in_declaration", "Discourage declaration-time initialization.", "Initialize state in reset or constructors instead of declarations.", r"\b(?:logic|bit|int|integer|byte|shortint|longint)\b[^;=]*=", "warning"),
    PatternRuleSpec("SV053", "require_default_nettype_none", "Require default_nettype none in files with modules.", "Add `default_nettype none to files that declare modules.", r"^\s*module\b", "warning", "required_file_if", r"^\s*`default_nettype\s+none\b"),
    PatternRuleSpec("SV054", "require_timeunit_timeprecision", "Require timeunit/timeprecision in files with modules.", "Declare timeunit and timeprecision in files that declare modules.", r"^\s*module\b", "warning", "required_file_if", r"^\s*timeunit\b[\s\S]*^\s*timeprecision\b"),
]

SV_COMMUNITY_RULES = [build_pattern_rule_class(spec) for spec in SV_COMMUNITY_SPECS]
